"""remove ai table

Revision ID: d97d35a9d705
Revises: 970e1796100a
Create Date: 2026-02-09 15:23:30.399913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97d35a9d705'
down_revision: Union[str, Sequence[str], None] = '970e1796100a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_id', table_name='ai')
    op.drop_table('ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_pkey')
    )
    op.create_index('ix_ai_id', 'ai', ['id'], unique=False)
    # ### end Alembic commands ###
